In [4]:
import sys
print(sys.executable)

C:\Users\aahan\OneDrive\Desktop\Deep Learning\SciEmbed\env\Scripts\python.exe

In [30]:
import pandas as pd
import re

<h1>Pre-processing Pipeline</h1>

In [31]:
df = pd.read_csv("../data/arxiv_dataset.csv")

In [32]:
df.head()

,id,title,summary,published,authors,categories
0,http://arxiv.org/abs/0705.0602v1,Risk Assessment Algorithms Based On Recursive ...,The assessment of highly-risky situations at...,2007-05-04 11:53:35+00:00,"['Alejandro Chinea Manrique De Lara', 'Michel ...",['cs.NE']
1,http://arxiv.org/abs/0705.1013v4,Tracking User Attention in Collaborative Taggi...,Collaborative tagging has recently attracted...,2007-05-07 23:57:46+00:00,"['Elizeu Santos-Neto', 'Matei Ripeanu', 'Adria...","['cs.CY', 'cs.DL']"
2,http://arxiv.org/abs/0708.0927v1,Modeling Visual Information Processing in Brai...,"We live in the Information Age, and informat...",2007-08-07 11:16:15+00:00,['Emanuel Diamant'],"['cs.CV', 'cs.AI']"
3,http://arxiv.org/abs/0709.4141v1,On representation theory of affine Hecke algeb...,Ariki's and Grojnowski's approach to the rep...,2007-09-26 11:55:24+00:00,['Vanessa Miemietz'],['math.RT']
4,http://arxiv.org/abs/0711.0795v4,Finite-Dimensional Representations of Hyper Lo...,We study finite-dimensional representations ...,2007-11-06 03:42:55+00:00,"['Dijana Jakelic', 'Adriano Moura']","['math.AG', 'math.RT']"

In [33]:
df['title'].isna().sum()

np.int64(0)

In [34]:
df['summary'].isna().sum()

np.int64(0)

In [35]:
#new line count
print(df['title'].str.count(r'\n').sum())
print(df['summary'].str.count(r'\n').sum())

0
179

In [36]:
#spaces count
print(df['summary'].str.count(r'\s').sum())
print(df['title'].str.count(r'\s').sum())

544589
27473

In [37]:
#tabs count
print(df['summary'].str.count(r'\t').sum())
print(df['title'].str.count(r'\t').sum())

0
0

In [38]:
#multi-space count
print(df['summary'].str.count(r' {2,}').sum())
print(df['title'].str.count(r' {2,}').sum())

256
0

In [39]:
#need to remove newline, tabs and multiple spaces

In [41]:
df['summary'] = df['summary'].str.replace("\n", " ", regex = "False")
df['summary'] = df['summary'].str.replace("\t", " ", regex = "False")
print(df['summary'].str.count(r'\t').sum())
print(df['summary'].str.count(r'\n').sum())

0
0

In [42]:
#combining into one function

def cleaner(text):
    text = str(text)

    #replace newlines and tabs
    text = text.replace("\n", " ")
    text = text.replace("\t", " ")

    #replace multiple spaces
    text = re.sub(r"\s+", " ", text)

    #strip trailing and leading spaces
    text = text.strip()

    return text

In [43]:
df['title'] = df['title'].apply(cleaner)
df['summary'] = df['summary'].apply(cleaner)

print(df['title'].str.count(r'\n').sum())
print(df['summary'].str.count(r'\n').sum())
print(df['summary'].str.count(r'\t').sum())
print(df['title'].str.count(r'\t').sum())
print(df['summary'].str.count(r' {2,}').sum())
print(df['title'].str.count(r' {2,}').sum())

0
0
0
0
0
0

In [44]:
df.head()

,id,title,summary,published,authors,categories
0,http://arxiv.org/abs/0705.0602v1,Risk Assessment Algorithms Based On Recursive ...,The assessment of highly-risky situations at r...,2007-05-04 11:53:35+00:00,"['Alejandro Chinea Manrique De Lara', 'Michel ...",['cs.NE']
1,http://arxiv.org/abs/0705.1013v4,Tracking User Attention in Collaborative Taggi...,Collaborative tagging has recently attracted t...,2007-05-07 23:57:46+00:00,"['Elizeu Santos-Neto', 'Matei Ripeanu', 'Adria...","['cs.CY', 'cs.DL']"
2,http://arxiv.org/abs/0708.0927v1,Modeling Visual Information Processing in Brai...,"We live in the Information Age, and informatio...",2007-08-07 11:16:15+00:00,['Emanuel Diamant'],"['cs.CV', 'cs.AI']"
3,http://arxiv.org/abs/0709.4141v1,On representation theory of affine Hecke algeb...,Ariki's and Grojnowski's approach to the repre...,2007-09-26 11:55:24+00:00,['Vanessa Miemietz'],['math.RT']
4,http://arxiv.org/abs/0711.0795v4,Finite-Dimensional Representations of Hyper Lo...,We study finite-dimensional representations of...,2007-11-06 03:42:55+00:00,"['Dijana Jakelic', 'Adriano Moura']","['math.AG', 'math.RT']"

In [45]:
df['document'] = df['title'] + " " + df['summary']

df.head()

,id,title,summary,published,authors,categories,document
0,http://arxiv.org/abs/0705.0602v1,Risk Assessment Algorithms Based On Recursive ...,The assessment of highly-risky situations at r...,2007-05-04 11:53:35+00:00,"['Alejandro Chinea Manrique De Lara', 'Michel ...",['cs.NE'],Risk Assessment Algorithms Based On Recursive ...
1,http://arxiv.org/abs/0705.1013v4,Tracking User Attention in Collaborative Taggi...,Collaborative tagging has recently attracted t...,2007-05-07 23:57:46+00:00,"['Elizeu Santos-Neto', 'Matei Ripeanu', 'Adria...","['cs.CY', 'cs.DL']",Tracking User Attention in Collaborative Taggi...
2,http://arxiv.org/abs/0708.0927v1,Modeling Visual Information Processing in Brai...,"We live in the Information Age, and informatio...",2007-08-07 11:16:15+00:00,['Emanuel Diamant'],"['cs.CV', 'cs.AI']",Modeling Visual Information Processing in Brai...
3,http://arxiv.org/abs/0709.4141v1,On representation theory of affine Hecke algeb...,Ariki's and Grojnowski's approach to the repre...,2007-09-26 11:55:24+00:00,['Vanessa Miemietz'],['math.RT'],On representation theory of affine Hecke algeb...
4,http://arxiv.org/abs/0711.0795v4,Finite-Dimensional Representations of Hyper Lo...,We study finite-dimensional representations of...,2007-11-06 03:42:55+00:00,"['Dijana Jakelic', 'Adriano Moura']","['math.AG', 'math.RT']",Finite-Dimensional Representations of Hyper Lo...

In [65]:
df = df[df['document'].str.strip() != ""]

In [69]:
print(df.shape[0])

3289

In [70]:
df = df.drop_duplicates(subset = ['document'])

print(df.shape[0])

3289

In [71]:
df.head()

,id,title,summary,published,authors,categories,document
0,http://arxiv.org/abs/0705.0602v1,Risk Assessment Algorithms Based On Recursive ...,The assessment of highly-risky situations at r...,2007-05-04 11:53:35+00:00,"['Alejandro Chinea Manrique De Lara', 'Michel ...",['cs.NE'],Risk Assessment Algorithms Based On Recursive ...
1,http://arxiv.org/abs/0705.1013v4,Tracking User Attention in Collaborative Taggi...,Collaborative tagging has recently attracted t...,2007-05-07 23:57:46+00:00,"['Elizeu Santos-Neto', 'Matei Ripeanu', 'Adria...","['cs.CY', 'cs.DL']",Tracking User Attention in Collaborative Taggi...
2,http://arxiv.org/abs/0708.0927v1,Modeling Visual Information Processing in Brai...,"We live in the Information Age, and informatio...",2007-08-07 11:16:15+00:00,['Emanuel Diamant'],"['cs.CV', 'cs.AI']",Modeling Visual Information Processing in Brai...
3,http://arxiv.org/abs/0709.4141v1,On representation theory of affine Hecke algeb...,Ariki's and Grojnowski's approach to the repre...,2007-09-26 11:55:24+00:00,['Vanessa Miemietz'],['math.RT'],On representation theory of affine Hecke algeb...
4,http://arxiv.org/abs/0711.0795v4,Finite-Dimensional Representations of Hyper Lo...,We study finite-dimensional representations of...,2007-11-06 03:42:55+00:00,"['Dijana Jakelic', 'Adriano Moura']","['math.AG', 'math.RT']",Finite-Dimensional Representations of Hyper Lo...